sonar.projectKey=sonarInit2
sonar.projectName=sonarInit2
sonar.projectVersion=1.0

# Codigo fuente Python del proyecto
sonar.sources=backend
sonar.sourceEncoding=UTF-8

# Analizar solo archivos Python
sonar.inclusions=**/*.ts,**/*.tsx,**/*.css
sonar.language=python

# Excluir artefactos no relevantes
sonar.exclusions=**/migrations/**,**/__pycache__/**,**/venv/**,**/env/**,**/*.pyc,**/node_modules/**,**/static/**,**/node_modules/**

# Tests
sonar.tests=backend
sonar.test.inclusions=**/tests/**/*.py,**/test_*.py
sonar.javascript.node.maxspace=4096