sonar.projectKey=SpeakBranch
sonar.projectName=SpeakBranch
sonar.projectVersion=1.0
sonar.sources=attempts,backend,courses,exams,questions,users,vocabulary
sonar.sourceEncoding=UTF-8
sonar.inclusions=**/*.py
sonar.exclusions=**/migrations/**,**/__pycache__/**,**/venv/**,**/env/**,**/*.pyc,**/node_modules/**,**/static/**
sonar.tests=attempts,courses,exams,questions,users,vocabulary
sonar.test.inclusions=**/tests/**/*.py,**/test_*.py