# Generated by Django 6.0.3 on 2026-03-15 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeningAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listening_type', models.CharField(choices=[('LISTENING_SHADOWING', 'Listening Shadowing'), ('LISTENING_COMPREHENSION', 'Listening Comprehension')], max_length=30, verbose_name='tipo de listening')),
                ('transcribed_text', models.TextField(blank=True, help_text='Texto devuelto por Whisper', null=True, verbose_name='texto transcrito')),
                ('transcription_match', models.FloatField(blank=True, null=True, verbose_name='coincidencia de transcripción')),
                ('selected_answer', models.TextField(blank=True, null=True, verbose_name='respuesta seleccionada')),
                ('correct', models.BooleanField(blank=True, null=True, verbose_name='es correcta')),
                ('replays_used', models.IntegerField(default=0, help_text='Cuántas veces reprodujo el audio', verbose_name='repeticiones usadas')),
                ('score', models.FloatField(blank=True, help_text='0-100', null=True, verbose_name='puntuación')),
                ('difficulty', models.CharField(choices=[('EASY', 'Fácil'), ('MEDIUM', 'Medio'), ('HARD', 'Difícil')], max_length=10, verbose_name='dificultad')),
                ('xp_earned', models.IntegerField(default=0, verbose_name='XP ganado')),
                ('api_response_raw', models.JSONField(blank=True, null=True, verbose_name='respuesta raw de API')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha del intento')),
                ('question', models.ForeignKey(limit_choices_to={'type__in': ['LISTENING_SHADOWING', 'LISTENING_COMPREHENSION']}, on_delete=django.db.models.deletion.CASCADE, related_name='listening_attempts', to='questions.question', verbose_name='pregunta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_attempts', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'Intento de Listening',
                'verbose_name_plural': 'Intentos de Listening',
                'db_table': 'listening_attempts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='listening_a_user_id_c241bd_idx'), models.Index(fields=['listening_type'], name='listening_a_listeni_82b846_idx'), models.Index(fields=['question'], name='listening_a_questio_572067_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReadingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.TextField(verbose_name='respuesta seleccionada')),
                ('correct', models.BooleanField(default=False, verbose_name='es correcta')),
                ('score', models.FloatField(blank=True, help_text='0-100', null=True, verbose_name='puntuación')),
                ('difficulty', models.CharField(choices=[('EASY', 'Fácil'), ('MEDIUM', 'Medio'), ('HARD', 'Difícil')], max_length=10, verbose_name='dificultad')),
                ('xp_earned', models.IntegerField(default=0, verbose_name='XP ganado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha del intento')),
                ('question', models.ForeignKey(limit_choices_to={'type': 'READING'}, on_delete=django.db.models.deletion.CASCADE, related_name='reading_attempts', to='questions.question', verbose_name='pregunta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_attempts', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'Intento de Reading',
                'verbose_name_plural': 'Intentos de Reading',
                'db_table': 'reading_attempts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='reading_att_user_id_1abf92_idx'), models.Index(fields=['question'], name='reading_att_questio_e7a40c_idx'), models.Index(fields=['correct'], name='reading_att_correct_f97cc5_idx'), models.Index(fields=['difficulty'], name='reading_att_difficu_55b8a7_idx')],
            },
        ),
        migrations.CreateModel(
            name='SpeakingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_text', models.TextField(verbose_name='texto esperado')),
                ('transcribed_text', models.TextField(blank=True, help_text='Texto devuelto por Whisper', null=True, verbose_name='texto transcrito')),
                ('transcription_match', models.FloatField(blank=True, help_text='Similitud 0.0 a 1.0 (rapidfuzz)', null=True, verbose_name='coincidencia de transcripción')),
                ('score', models.FloatField(blank=True, help_text='0-100', null=True, verbose_name='puntuación')),
                ('difficulty', models.CharField(choices=[('EASY', 'Fácil'), ('MEDIUM', 'Medio'), ('HARD', 'Difícil')], max_length=10, verbose_name='dificultad')),
                ('attempts_count', models.IntegerField(default=1, help_text='Reintentos del mismo ejercicio', verbose_name='número de intentos')),
                ('xp_earned', models.IntegerField(default=0, verbose_name='XP ganado')),
                ('api_response_raw', models.JSONField(blank=True, help_text='Respuesta raw de OpenAI Whisper', null=True, verbose_name='respuesta raw de API')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha del intento')),
                ('question', models.ForeignKey(limit_choices_to={'type': 'SPEAKING'}, on_delete=django.db.models.deletion.CASCADE, related_name='speaking_attempts', to='questions.question', verbose_name='pregunta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_attempts', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'Intento de Speaking',
                'verbose_name_plural': 'Intentos de Speaking',
                'db_table': 'speaking_attempts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='speaking_at_user_id_57ba88_idx'), models.Index(fields=['question'], name='speaking_at_questio_405bf1_idx'), models.Index(fields=['difficulty'], name='speaking_at_difficu_04038b_idx'), models.Index(fields=['score'], name='speaking_at_score_f693d9_idx')],
            },
        ),
        migrations.CreateModel(
            name='WritingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_text', models.TextField(help_text='Instrucción del ejercicio', verbose_name='instrucción')),
                ('student_text', models.TextField(verbose_name='texto del alumno')),
                ('score_grammar', models.FloatField(blank=True, null=True, verbose_name='puntuación de gramática')),
                ('score_vocabulary', models.FloatField(blank=True, null=True, verbose_name='puntuación de vocabulario')),
                ('score_coherence', models.FloatField(blank=True, null=True, verbose_name='puntuación de coherencia')),
                ('score_spelling', models.FloatField(blank=True, null=True, verbose_name='puntuación de ortografía')),
                ('score', models.FloatField(blank=True, help_text='0-100 (grammar 35% + vocabulary 25% + coherence 25% + spelling 15%)', null=True, verbose_name='puntuación total')),
                ('ai_feedback', models.TextField(blank=True, help_text='Feedback generado por OpenAI GPT', null=True, verbose_name='feedback de IA')),
                ('difficulty', models.CharField(choices=[('EASY', 'Fácil'), ('MEDIUM', 'Medio'), ('HARD', 'Difícil')], max_length=10, verbose_name='dificultad')),
                ('xp_earned', models.IntegerField(default=0, verbose_name='XP ganado')),
                ('api_response_raw', models.JSONField(blank=True, help_text='Respuesta raw de OpenAI', null=True, verbose_name='respuesta raw de API')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha del intento')),
                ('question', models.ForeignKey(limit_choices_to={'type': 'WRITING'}, on_delete=django.db.models.deletion.CASCADE, related_name='writing_attempts', to='questions.question', verbose_name='pregunta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_attempts', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'Intento de Writing',
                'verbose_name_plural': 'Intentos de Writing',
                'db_table': 'writing_attempts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='writing_att_user_id_5fb4a3_idx'), models.Index(fields=['question'], name='writing_att_questio_b92fc3_idx'), models.Index(fields=['difficulty'], name='writing_att_difficu_b38c8c_idx')],
            },
        ),
    ]
