# Generated by Django 6.0.3 on 2026-03-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeningattempt',
            name='correct',
            field=models.BooleanField(blank=True, default=False, verbose_name='es correcta'),
        ),
        migrations.AlterField(
            model_name='listeningattempt',
            name='selected_answer',
            field=models.TextField(blank=True, default='', verbose_name='respuesta seleccionada'),
        ),
        migrations.AlterField(
            model_name='listeningattempt',
            name='transcribed_text',
            field=models.TextField(blank=True, default='', help_text='Texto devuelto por Whisper', verbose_name='texto transcrito'),
        ),
        migrations.AlterField(
            model_name='speakingattempt',
            name='transcribed_text',
            field=models.TextField(blank=True, default='', help_text='Texto devuelto por Whisper', verbose_name='texto transcrito'),
        ),
        migrations.AlterField(
            model_name='writingattempt',
            name='ai_feedback',
            field=models.TextField(blank=True, default='', help_text='Feedback generado por OpenAI GPT', verbose_name='feedback de IA'),
        ),
    ]
