# Generated by Django 6.0.3 on 2026-04-12 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0002_alter_listeningattempt_correct_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttemptLessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('READING', 'Reading'), ('SPEAKING', 'Speaking'), ('LISTENING_SHADOWING', 'Listening Shadowing'), ('LISTENING_COMPREHENSION', 'Listening Comprehension'), ('WRITING', 'Writing')], max_length=30, verbose_name='tipo de pregunta')),
                ('question_level', models.CharField(max_length=5, verbose_name='nivel')),
                ('xp_easy', models.IntegerField(default=0, verbose_name='XP ganado en EASY')),
                ('xp_medium', models.IntegerField(default=0, verbose_name='XP ganado en MEDIUM')),
                ('xp_hard', models.IntegerField(default=0, verbose_name='XP ganado en HARD')),
                ('hard_correct_attempts', models.IntegerField(default=0, help_text='Cuenta de respuestas correctas en HARD', verbose_name='aciertos en HARD')),
                ('is_completed', models.BooleanField(default=False, verbose_name='lección completada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_lesson_progress', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'Progreso de Lección de Intentos',
                'verbose_name_plural': 'Progreso de Lecciones de Intentos',
                'db_table': 'attempt_lesson_progress',
                'indexes': [models.Index(fields=['user', 'question_type', 'question_level'], name='attempt_les_user_id_a8fc1b_idx'), models.Index(fields=['is_completed'], name='attempt_les_is_comp_58a43f_idx')],
                'unique_together': {('user', 'question_type', 'question_level')},
            },
        ),
    ]
