# Generated by Django 6.0.3 on 2026-04-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0003_attemptlessonprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attemptlessonprogress',
            name='hard_correct_attempts',
        ),
        migrations.AlterField(
            model_name='attemptlessonprogress',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='lección completada (total_xp >= 60)'),
        ),
        migrations.AlterField(
            model_name='attemptlessonprogress',
            name='question_level',
            field=models.CharField(help_text='Ej: A1, A2, B1', max_length=5, verbose_name='nivel del usuario (A1, A2, B1, etc)'),
        ),
        migrations.AlterField(
            model_name='attemptlessonprogress',
            name='xp_easy',
            field=models.IntegerField(default=0, help_text='Máximo 10', verbose_name='XP ganado en ejercicios EASY'),
        ),
        migrations.AlterField(
            model_name='attemptlessonprogress',
            name='xp_hard',
            field=models.IntegerField(default=0, help_text='Máximo 30', verbose_name='XP ganado en ejercicios HARD'),
        ),
        migrations.AlterField(
            model_name='attemptlessonprogress',
            name='xp_medium',
            field=models.IntegerField(default=0, help_text='Máximo 20', verbose_name='XP ganado en ejercicios MEDIUM'),
        ),
    ]
