# Generated by Django 6.0.3 on 2026-03-15 00:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('A1', 'Beginner (A1)'), ('A2', 'Elementary (A2)'), ('B1', 'Intermediate (B1)'), ('B2', 'Upper Intermediate (B2)'), ('C1', 'Advanced (C1)'), ('C2', 'Proficient (C2)')], max_length=5, verbose_name='nivel')),
                ('type', models.CharField(choices=[('DIAGNOSTIC', 'Examen de Diagnóstico'), ('LEVEL_UP', 'Examen de Nivelación'), ('TOEFL', 'Examen TOEFL')], max_length=15, verbose_name='tipo de examen')),
                ('name', models.CharField(help_text='Nombre descriptivo del examen', max_length=200, verbose_name='nombre del examen')),
                ('description', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('xp_required', models.IntegerField(default=0, help_text='Umbral de XP para desbloquear', validators=[django.core.validators.MinValueValidator(0)], verbose_name='XP requerido')),
                ('passing_score', models.IntegerField(default=70, help_text='Puntuación mínima para aprobar (0-100)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='puntuación mínima')),
                ('time_limit_minutes', models.IntegerField(default=60, validators=[django.core.validators.MinValueValidator(1)], verbose_name='límite de tiempo (minutos)')),
                ('question_count', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='número de preguntas')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
            ],
            options={
                'verbose_name': 'Examen',
                'verbose_name_plural': 'Exámenes',
                'db_table': 'exams',
                'ordering': ['level', 'type', 'name'],
                'indexes': [models.Index(fields=['level', 'type'], name='exams_level_15ecfe_idx'), models.Index(fields=['xp_required'], name='exams_xp_requ_31c44a_idx'), models.Index(fields=['is_active'], name='exams_is_acti_5cee66_idx')],
                'unique_together': {('level', 'type')},
            },
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'En progreso'), ('COMPLETED', 'Completado'), ('EXPIRED', 'Expirado')], default='IN_PROGRESS', max_length=15, verbose_name='estado')),
                ('score', models.FloatField(blank=True, help_text='Puntuación total del examen (0-100)', null=True, verbose_name='puntuación')),
                ('passed', models.BooleanField(default=False, verbose_name='aprobado')),
                ('xp_earned', models.IntegerField(default=0, verbose_name='XP ganado')),
                ('answers', models.JSONField(blank=True, default=dict, help_text='Diccionario con {pregunta_id: respuesta}', verbose_name='respuestas')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de inicio')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de completado')),
                ('time_spent_seconds', models.IntegerField(default=0, verbose_name='tiempo empleado (segundos)')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exams.exam', verbose_name='examen')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'Intento de Examen',
                'verbose_name_plural': 'Intentos de Exámenes',
                'db_table': 'exam_attempts',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['user', '-started_at'], name='exam_attemp_user_id_18e020_idx'), models.Index(fields=['exam', 'status'], name='exam_attemp_exam_id_33f189_idx'), models.Index(fields=['passed'], name='exam_attemp_passed_4d7b19_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, help_text='Orden de la pregunta en el examen', verbose_name='orden')),
                ('points', models.IntegerField(default=10, help_text='Puntos que vale esta pregunta', verbose_name='puntos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_questions', to='exams.exam', verbose_name='examen')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='questions.question', verbose_name='pregunta')),
            ],
            options={
                'verbose_name': 'Pregunta de Examen',
                'verbose_name_plural': 'Preguntas de Exámenes',
                'db_table': 'exam_questions',
                'ordering': ['exam', 'order'],
                'indexes': [models.Index(fields=['exam', 'order'], name='exam_questi_exam_id_a0918d_idx'), models.Index(fields=['question'], name='exam_questi_questio_14f54c_idx')],
                'unique_together': {('exam', 'order'), ('exam', 'question')},
            },
        ),
        migrations.CreateModel(
            name='UnlockedExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de desbloqueo')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_by', to='exams.exam', verbose_name='examen')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_exams', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'Examen Desbloqueado',
                'verbose_name_plural': 'Exámenes Desbloqueados',
                'db_table': 'user_unlocked_exams',
                'indexes': [models.Index(fields=['user', 'unlocked_at'], name='user_unlock_user_id_db491b_idx'), models.Index(fields=['exam'], name='user_unlock_exam_id_6ac8eb_idx')],
                'unique_together': {('user', 'exam')},
            },
        ),
    ]
