# Generated by Django 6.0.3 on 2026-03-14 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre del curso')),
                ('level', models.CharField(choices=[('A1', 'Beginner (A1)'), ('A2', 'Elementary (A2)'), ('B1', 'Intermediate (B1)'), ('B2', 'Upper Intermediate (B2)'), ('C1', 'Advanced (C1)'), ('C2', 'Proficient (C2)')], max_length=5, verbose_name='nivel')),
                ('description', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'db_table': 'courses',
                'ordering': ['level', 'name'],
                'indexes': [models.Index(fields=['level'], name='courses_level_838724_idx'), models.Index(fields=['name'], name='courses_name_dcd600_idx')],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('order_index', models.IntegerField(default=0, help_text='Define el orden obligatorio de la lección', verbose_name='índice de orden')),
                ('content_type', models.CharField(choices=[('VIDEO', 'Video'), ('TEXT', 'Texto'), ('EXERCISE_READING', 'Ejercicio de Reading'), ('EXERCISE_SPEAKING', 'Ejercicio de Speaking'), ('EXERCISE_LISTENING_SHADOWING', 'Ejercicio de Listening Shadowing'), ('EXERCISE_LISTENING_COMPREHENSION', 'Ejercicio de Listening Comprehension'), ('EXERCISE_WRITING', 'Ejercicio de Writing')], max_length=40, verbose_name='tipo de contenido')),
                ('content_url', models.URLField(blank=True, help_text='URL del audio/video/texto', max_length=500, null=True, verbose_name='URL del contenido')),
                ('duration_min', models.IntegerField(default=5, verbose_name='duración (minutos)')),
                ('xp_value', models.IntegerField(default=10, help_text='XP base por completar la lección', verbose_name='valor de XP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course', verbose_name='curso')),
            ],
            options={
                'verbose_name': 'Lección',
                'verbose_name_plural': 'Lecciones',
                'db_table': 'lessons',
                'ordering': ['course', 'order_index'],
            },
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de inscripción')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de completado')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course', verbose_name='curso')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
                ('current_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='courses.lesson', verbose_name='lección actual')),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
                'db_table': 'course_enrollments',
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False, verbose_name='completada')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de completado')),
                ('score', models.FloatField(blank=True, help_text='Score obtenido en la lección', null=True, verbose_name='puntuación')),
                ('xp_earned', models.IntegerField(default=0, verbose_name='XP ganado')),
                ('attempts', models.IntegerField(default=1, help_text='Número de intentos realizados', verbose_name='intentos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='courses.lesson', verbose_name='lección')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'Progreso de Lección',
                'verbose_name_plural': 'Progresos de Lecciones',
                'db_table': 'lesson_progress',
            },
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['course', 'order_index'], name='lessons_course__5566eb_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['content_type'], name='lessons_content_20a3e8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('course', 'order_index')},
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['user', 'course'], name='course_enro_user_id_42cd6e_idx'),
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['enrolled_at'], name='course_enro_enrolle_2df4d2_idx'),
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['completed_at'], name='course_enro_complet_ccc53d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='courseenrollment',
            unique_together={('user', 'course')},
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['user', 'completed'], name='lesson_prog_user_id_505c40_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['lesson'], name='lesson_prog_lesson__568578_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['completed_at'], name='lesson_prog_complet_ffaf8c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lessonprogress',
            unique_together={('user', 'lesson')},
        ),
    ]
