# Generated by Django 6.0.3 on 2026-03-26 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('A1', 'Beginner (A1)'), ('A2', 'Elementary (A2)'), ('B1', 'Intermediate (B1)'), ('B2', 'Upper Intermediate (B2)')], help_text='Un curso solo puede tener UN nivel CEFR', max_length=5, verbose_name='nivel'),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='attempts',
            field=models.IntegerField(default=0, help_text='Número de intentos realizados', verbose_name='intentos'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('name', 'level'), name='unique_course_name_per_level'),
        ),
    ]
