# Generated by Django 6.0.3 on 2026-03-15 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vocabulary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='texto de la pregunta')),
                ('type', models.CharField(choices=[('SPEAKING', 'Speaking'), ('READING', 'Reading'), ('LISTENING_SHADOWING', 'Listening Shadowing'), ('LISTENING_COMPREHENSION', 'Listening Comprehension'), ('WRITING', 'Writing')], max_length=30, verbose_name='tipo de ejercicio')),
                ('level', models.CharField(choices=[('A1', 'Beginner (A1)'), ('A2', 'Elementary (A2)'), ('B1', 'Intermediate (B1)'), ('B2', 'Upper Intermediate (B2)'), ('C1', 'Advanced (C1)'), ('C2', 'Proficient (C2)')], max_length=5, verbose_name='nivel')),
                ('category', models.CharField(choices=[('TOEFL', 'TOEFL'), ('BASIC', 'Básico'), ('INTERMEDIATE', 'Intermedio'), ('ADVANCED', 'Avanzado')], max_length=20, verbose_name='categoría')),
                ('correct_answer', models.TextField(verbose_name='respuesta correcta')),
                ('audio_url', models.URLField(blank=True, help_text='URL del audio pregrabado (TTS)', max_length=500, null=True, verbose_name='URL del audio')),
                ('phonetic_text', models.CharField(blank=True, help_text='Transcripción IPA ej: /dɒɡ/', max_length=300, null=True, verbose_name='transcripción fonética')),
                ('difficulty', models.CharField(choices=[('EASY', 'Fácil'), ('MEDIUM', 'Medio'), ('HARD', 'Difícil')], default='MEDIUM', max_length=10, verbose_name='dificultad')),
                ('xp_max', models.IntegerField(default=20, help_text='EASY=10, MEDIUM=20, HARD=30', verbose_name='XP máximo')),
                ('max_replays', models.IntegerField(blank=True, help_text='NULL=ilimitado (shadowing), 3=comprensión', null=True, verbose_name='repeticiones máximas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'db_table': 'questions',
                'ordering': ['level', 'difficulty', 'type'],
            },
        ),
        migrations.CreateModel(
            name='QuestionVocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_items', to='questions.question', verbose_name='pregunta')),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='vocabulary.vocabulary', verbose_name='vocabulario')),
            ],
            options={
                'verbose_name': 'Vocabulario de Pregunta',
                'verbose_name_plural': 'Vocabulario de Preguntas',
                'db_table': 'question_vocabulary',
            },
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['type', 'level', 'difficulty'], name='questions_type_2e6ee5_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['category'], name='questions_categor_3ee678_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['created_by'], name='questions_created_59d8b2_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['is_active'], name='questions_is_acti_ba6b3c_idx'),
        ),
        migrations.AddIndex(
            model_name='questionvocabulary',
            index=models.Index(fields=['question'], name='question_vo_questio_c75ff8_idx'),
        ),
        migrations.AddIndex(
            model_name='questionvocabulary',
            index=models.Index(fields=['vocabulary'], name='question_vo_vocabul_ec2535_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='questionvocabulary',
            unique_together={('question', 'vocabulary')},
        ),
    ]
