# Generated by Django 6.0.3 on 2026-04-03 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('DIAGNOSTIC', 'Examen diagnóstico'), ('PRACTICE', 'Solo ejercicio'), ('LEVEL_UP', 'Examen subir nivel')], max_length=20, verbose_name='categoría'),
        ),
        migrations.AlterField(
            model_name='question',
            name='phonetic_text',
            field=models.CharField(blank=True, help_text='Transcripción IPA ej: /dɒɡ/', max_length=300, verbose_name='transcripción fonética'),
        ),
    ]
