# Generated by Django 6.0.3 on 2026-04-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_add_is_key_and_order_to_question_vocabulary'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='questionvocabulary',
            new_name='question_vo_is_key_144cd5_idx',
            old_name='question_v_is_key_order_idx',
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('TOEFL', 'TOEFL'), ('BASIC', 'Básico'), ('INTERMEDIATE', 'Intermedio'), ('ADVANCED', 'Avanzado'), ('DIAGNOSTIC', 'Diagnóstico')], max_length=20, verbose_name='categoría'),
        ),
    ]
