# Generated by Django 6.0.3 on 2026-04-14 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_rename_question_v_is_key_order_idx_question_vo_is_key_144cd5_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['type', 'level', 'difficulty'], 'verbose_name': 'Pregunta', 'verbose_name_plural': 'Preguntas'},
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('TOEFL', 'TOEFL'), ('BASIC', 'Básico'), ('INTERMEDIATE', 'Intermedio'), ('ADVANCED', 'Avanzado'), ('DIAGNOSTIC', 'Diagnóstico'), ('PRACTICE', 'Solo ejercicio'), ('LEVEL_UP', 'Examen subir nivel')], max_length=20, verbose_name='categoría'),
        ),
        migrations.AlterField(
            model_name='question',
            name='phonetic_text',
            field=models.TextField(blank=True, help_text='IPA ej: /dɒɡ/ — o pasaje completo para TTS en listening', verbose_name='transcripción fonética / texto TTS'),
        ),
    ]
