# Generated by Django 6.0.3 on 2026-04-08 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adaptive_threshold_up', models.FloatField(default=16.0)),
                ('adaptive_threshold_down', models.FloatField(default=10.0)),
                ('registered_enable', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'db_table': 'system_config',
            },
        ),
    ]
