# Generated by Django 6.0.3 on 2026-04-11 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_config', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemconfig',
            old_name='registered_enable',
            new_name='registration_enabled',
        ),
    ]
