# Generated by Django 6.0.3 on 2026-04-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_config', '0002_rename_registered_enable_systemconfig_registration_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='level_xp_requirements',
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='XP requerido por nivel para habilitar examen de subida. Ej: {"A1": 200, "A2": 500}'
            ),
        ),
    ]
