# Generated by Django 6.0.3 on 2026-04-16 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_config', '0003_systemconfig_xp_levels'),
        ('system_config', '0005_update_level_scale_a1_b2'),
    ]

    operations = [
    ]
