# Generated by Django 6.0.3 on 2026-04-16 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_config', '0006_merge_20260416_0253'),
        ('system_config', '0007_remove_level_xp_requirements'),
    ]

    operations = [
    ]
