# Generated by Django 6.0.3 on 2026-03-15 00:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, max_length=200, verbose_name='palabra')),
                ('meaning', models.TextField(verbose_name='significado')),
                ('pronunciation', models.CharField(blank=True, help_text='Ej: /dɒɡ/', max_length=200, null=True, verbose_name='pronunciación')),
                ('example_sentence', models.TextField(blank=True, null=True, verbose_name='oración de ejemplo')),
                ('level', models.CharField(choices=[('A1', 'Beginner (A1)'), ('A2', 'Elementary (A2)'), ('B1', 'Intermediate (B1)'), ('B2', 'Upper Intermediate (B2)'), ('C1', 'Advanced (C1)'), ('C2', 'Proficient (C2)')], max_length=5, verbose_name='nivel')),
                ('category', models.CharField(blank=True, help_text='Ej: Animals, Food, Business, etc.', max_length=50, null=True, verbose_name='categoría')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de imagen')),
                ('audio_url', models.URLField(blank=True, help_text='Pronunciación en audio', max_length=500, null=True, verbose_name='URL de audio')),
                ('daily_flag', models.BooleanField(default=False, help_text='Si está activo, puede aparecer en el vocabulario diario', verbose_name='incluir en vocabulario diario')),
                ('times_used', models.IntegerField(default=0, help_text='Número de veces que ha aparecido en vocabulario diario', verbose_name='veces utilizado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vocabulary_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
            ],
            options={
                'verbose_name': 'Vocabulario',
                'verbose_name_plural': 'Vocabulario',
                'db_table': 'vocabulary',
                'ordering': ['level', 'word'],
            },
        ),
        migrations.CreateModel(
            name='DailyVocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assigned', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='fecha de asignación')),
                ('was_seen', models.BooleanField(default=False, help_text='Si el usuario ha visto esta palabra', verbose_name='visto')),
                ('seen_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de vista')),
                ('was_practiced', models.BooleanField(default=False, help_text='Si el usuario practicó con esta palabra', verbose_name='practicado')),
                ('mastery_level', models.IntegerField(choices=[(0, 'No visto'), (1, 'Visto'), (2, 'En práctica'), (3, 'Aprendido'), (4, 'Dominado')], default=0, verbose_name='nivel de dominio')),
                ('times_reviewed', models.IntegerField(default=0, verbose_name='veces repasado')),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='último repaso')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_vocabulary', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_assignments', to='vocabulary.vocabulary', verbose_name='vocabulario')),
            ],
            options={
                'verbose_name': 'Vocabulario Diario',
                'verbose_name_plural': 'Vocabulario Diario',
                'db_table': 'daily_vocabulary',
                'ordering': ['-date_assigned', 'vocabulary__word'],
            },
        ),
        migrations.AddIndex(
            model_name='vocabulary',
            index=models.Index(fields=['word'], name='vocabulary_word_181c5a_idx'),
        ),
        migrations.AddIndex(
            model_name='vocabulary',
            index=models.Index(fields=['level', 'daily_flag'], name='vocabulary_level_1920c6_idx'),
        ),
        migrations.AddIndex(
            model_name='vocabulary',
            index=models.Index(fields=['category'], name='vocabulary_categor_b91bc8_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyvocabulary',
            index=models.Index(fields=['user', 'date_assigned'], name='daily_vocab_user_id_4e3a00_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyvocabulary',
            index=models.Index(fields=['user', 'mastery_level'], name='daily_vocab_user_id_0e10f4_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyvocabulary',
            index=models.Index(fields=['date_assigned', 'was_seen'], name='daily_vocab_date_as_409e4b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyvocabulary',
            unique_together={('vocabulary', 'user', 'date_assigned')},
        ),
    ]
