# Generated by Django 6.0.3 on 2026-03-14 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('password_hash', models.CharField(max_length=255, verbose_name='password')),
                ('first_name', models.CharField(max_length=100)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('NB', 'No binario'), ('P', 'Prefiero no decirlo')], max_length=20, null=True)),
                ('level', models.CharField(choices=[('A1', 'Beginner (A1)'), ('A2', 'Elementary (A2)'), ('B1', 'Intermediate (B1)'), ('B2', 'Upper Intermediate (B2)'), ('C1', 'Advanced (C1)'), ('C2', 'Proficient (C2)')], default='A1', max_length=5)),
                ('precision_speaking', models.FloatField(default=0.0)),
                ('precision_reading', models.FloatField(default=0.0)),
                ('precision_listening', models.FloatField(default=0.0)),
                ('precision_writing', models.FloatField(default=0.0)),
                ('role', models.CharField(choices=[('ADMIN', 'Administrador'), ('STUDENT', 'Estudiante')], default='STUDENT', max_length=10)),
                ('avatar_url', models.URLField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('A1', 'Beginner (A1)'), ('A2', 'Elementary (A2)'), ('B1', 'Intermediate (B1)'), ('B2', 'Upper Intermediate (B2)'), ('C1', 'Advanced (C1)'), ('C2', 'Proficient (C2)')], default='A1', max_length=5)),
                ('average_speaking', models.FloatField(default=0.0)),
                ('average_reading', models.FloatField(default=0.0)),
                ('average_listening', models.FloatField(default=0.0)),
                ('average_writing', models.FloatField(default=0.0)),
                ('total_xp', models.IntegerField(default=0)),
                ('streak_days', models.IntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progreso de Usuario',
                'verbose_name_plural': 'Progresos de Usuarios',
                'db_table': 'user_progress',
            },
        ),
        migrations.CreateModel(
            name='UserWeakCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('TOEFL', 'TOEFL'), ('BASIC', 'Básico'), ('INTERMEDIATE', 'Intermedio'), ('ADVANCED', 'Avanzado')], max_length=20)),
                ('skill', models.CharField(choices=[('SPEAKING', 'Speaking'), ('READING', 'Reading'), ('LISTENING_SHADOWING', 'Listening Shadowing'), ('LISTENING_COMPREHENSION', 'Listening Comprehension'), ('WRITING', 'Writing')], max_length=30)),
                ('avg_score', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weak_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Categoría Débil',
                'verbose_name_plural': 'Categorías Débiles',
                'db_table': 'user_weak_categories',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['level'], name='users_level_48a389_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='users_role_0ace22_idx'),
        ),
        migrations.AddIndex(
            model_name='userprogress',
            index=models.Index(fields=['user'], name='user_progre_user_id_77f83f_idx'),
        ),
        migrations.AddIndex(
            model_name='userprogress',
            index=models.Index(fields=['level'], name='user_progre_level_7877a8_idx'),
        ),
        migrations.AddIndex(
            model_name='userweakcategory',
            index=models.Index(fields=['user'], name='user_weak_c_user_id_a1b1c7_idx'),
        ),
        migrations.AddIndex(
            model_name='userweakcategory',
            index=models.Index(fields=['category', 'skill'], name='user_weak_c_categor_8ded98_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userweakcategory',
            unique_together={('user', 'category', 'skill')},
        ),
    ]
