# Generated by Django 6.0.3 on 2026-04-15

from django.db import migrations, models


def _add_legacy_columns_if_missing(apps, schema_editor):
    UserProgress = apps.get_model('users', 'UserProgress')

    table_name = UserProgress._meta.db_table
    existing_columns = {
        col.name for col in schema_editor.connection.introspection.get_table_description(
            schema_editor.connection.cursor(),
            table_name,
        )
    }

    if 'streak_freeze' not in existing_columns:
        field = models.IntegerField(default=0)
        field.set_attributes_from_name('streak_freeze')
        schema_editor.add_field(UserProgress, field)

    if 'skill_metrics' not in existing_columns:
        field = models.JSONField(default=dict, blank=True)
        field.set_attributes_from_name('skill_metrics')
        schema_editor.add_field(UserProgress, field)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprogress_level_start_xp'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(_add_legacy_columns_if_missing, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='userprogress',
                    name='streak_freeze',
                    field=models.IntegerField(default=0),
                ),
                migrations.AddField(
                    model_name='userprogress',
                    name='skill_metrics',
                    field=models.JSONField(blank=True, default=dict),
                ),
            ],
        ),
    ]
