# Generated by Django 6.0.3 on 2026-04-16 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprogress_streak_freeze_skill_metrics'),
        ('users', '0004_sync_userprogress_legacy_columns'),
    ]

    operations = [
    ]
