# Generated by Django 6.0.3 on 2026-04-16 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_merge_20260415_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprogress',
            name='skill_metrics',
            field=models.JSONField(default=dict),
        ),
    ]
