# Generated by Django 6.0.3 on 2026-04-16 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_add_skill_metrics_to_user_progress'),
        ('users', '0006_remove_userprogress_skill_metrics_user_created_by_and_more'),
    ]

    operations = [
    ]
